### ISSUE TITLE
LiveReloadServer has no attribute watcher

### ISSUE THREAD

**Issue by fgascon** [backstage/techdocs-container#15]
Starting with v0.3.0, I'm getting the following error when running the serve command in any project. It's not clear to me if that's a techdocs-container issue or a mkdocs-techdocs-core issue.

```
info: Starting mkdocs server.
verbose: [mkdocs] INFO     -  Building documentation...
verbose: [mkdocs] INFO     -  Cleaning site directory
verbose: [mkdocs] INFO     -  Documentation built in 0.27 seconds
verbose: [mkdocs] Traceback (most recent call last):
verbose: [mkdocs]   File "/usr/local/bin/mkdocs", line 8, in <module>
verbose: [mkdocs]     sys.exit(cli())
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
verbose: [mkdocs]     return self.main(*args, **kwargs)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
verbose: [mkdocs]     rv = self.invoke(ctx)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
verbose: [mkdocs]     return _process_result(sub_ctx.command.invoke(sub_ctx))
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
verbose: [mkdocs]     return ctx.invoke(self.callback, **ctx.params)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
verbose: [mkdocs]     return __callback(*args, **kwargs)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 173, in serve_command
verbose: [mkdocs]     serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 78, in serve
verbose: [mkdocs]     server = config['plugins'].run_event('serve', server, config=config, builder=builder)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
verbose: [mkdocs]     result = method(item, **kwargs)
verbose: [mkdocs]   File "/usr/local/lib/python3.8/site-packages/mkdocs_monorepo_plugin/plugin.py", line 67, in on_serve
verbose: [mkdocs]     buildfunc = list(server.watcher._tasks.values())[0]['func']
verbose: [mkdocs] AttributeError: 'LiveReloadServer' object has no attribute 'watcher'
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
```

**Comment by iamEAP** [comment]
It's 🐢 🐢 🐢  all the way down!  Underlying issue is backstage/mkdocs-monorepo-plugin#49, for which I have a fix coming soon.
