### ISSUE TITLE
LiveReload Issue

### ISSUE THREAD

**Issue by ahmed-alaa** [backstage/techdocs-container#9]
Hi,

I started to use the provided image and it keep logging an error related to LiveReload, any clue?

```
 TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
techdocs_1    | ERROR   -  Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
techdocs_1    | Traceback (most recent call last):
techdocs_1    |   File "/usr/local/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
techdocs_1    |     return self.callback()
techdocs_1    |   File "/usr/local/lib/python3.8/site-packages/livereload/handlers.py", line 69, in poll_tasks
techdocs_1    |     filepath, delay = cls.watcher.examine()
techdocs_1    |   File "/usr/local/lib/python3.8/site-packages/livereload/watcher.py", line 100, in examine
techdocs_1    |     changed = self.is_changed(path, item['ignore'])
techdocs_1    |   File "/usr/local/lib/python3.8/site-packages/livereload/watcher.py", line 135, in is_changed
techdocs_1    |     if os.path.isfile(path):
techdocs_1    |   File "/usr/local/lib/python3.8/genericpath.py", line 30, in isfile
```

Thanks

**Comment by OrkoHunter** [comment]
Hey! This is a known mkdocs issue and is fixed by defining `Nav` in your `mkdocs.yml` file.
See https://github.com/backstage/techdocs-cli/issues/26

**Comment by ahmed-alaa** [comment]
@OrkoHunter Thnx!
